### ISSUE TITLE
open source the complete code

### ISSUE THREAD

**Issue by ZhengFangWHU** [DPamK/BadAgent#1]
Hello, I am very interested in your work. When do you plan to open source the complete code?

**Comment by DPamK** [comment]
Thank you for your interest in our work. I apologize for any inconvenience, but I can confirm that we plan to open-source the majority of our code by July 12th at the latest.

**Comment by dongdongzhaoUP** [comment]
@DPamK Interesting work, looking forward to it!

**Comment by xunyuan-nuaa** [comment]
Hello, I am very interested in your work. When do you plan to open source the complete code including the main.py?

**Comment by Zhang-Henry** [comment]
Interesting work, looking forward to it!

**Comment by huizyuan** [comment]
Hi, I am very interest in this work, when does the code can be released completed?
