### ISSUE TITLE
How to apply it to my own dataset

### ISSUE THREAD

**Issue by breadxiexie** [DPamK/BadAgent#5]
What is the approximate process or dataset format required if I want to use my own data for backdoor embedding testing. Directly converting the dataset (Parquet format) used in the code to CSV format result in formatting errors. What should be the correct format?

**Comment by DPamK** [comment]
我这个工作还是基于比较早期的agent研究，在prompt中插入一些后门，目前比较流行的tools方式，其实用我们这个构造方法就不合适了。如果你要开始新的研究，并不需要延续我构造的后门注入方法，你可以考虑根据你们自己的数据的情况来重新写构造逻辑，只要最后那个数据能够使用LLM进行微调（无论是何种方式的微调），应该都是可行的

**Comment by breadxiexie** [comment]
那么如果我想要测试这种方法在其它数据集上的应用，遇到了一些数据集格式相关的问题。关于数据集格式有什么要求吗？
